boxuegu:
  url: ${BXG_URL:http://bxg-admin-open-api.boxuegu.com}

spring:
  redis:
    ################ Redis 基础配置 begin ##############
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: ${REDIS_HOST:redis-uat.boxuegu.com}
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: ${REDIS_PASSWORD:boxuegu}
    # 链接超时时间 单位 ms（毫秒）
    timeout: 10000
    ################ Redis 基础配置 end ##############
    ################ Redis 线程池设置 begin ##############
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
    ################ Redis 线程池设置 end ##############

